name: daily-monitoring
on:
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch:
jobs:
    monitoring_by_schedule:
        runs-on: ubuntu-latest
        permissions:
          issues: write
        steps:
            - name: 저장소 체크아웃
              uses: actions/checkout@v4

            - name: 파이썬 셋업
              uses: actions/setup-python@v5
              with:
                python-version: '3.9'
                
            - name: 의존성 설치
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
          
            - name: 모니터링 실행
              env:
                currency: ${{ vars.currency }}
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GH_OWNER: ${{ github.repository_owner }}
                GH_REPO: ${{ github.event.repository.name }}
              run: python main.py